### ISSUE TITLE
kgs_explore wiki example seems to work but finishes in seg-fault

### ISSUE THREAD

**Issue by CoChrists** [ExcitedStates/KGS#4] opened 2017-01-26 23:59 UTC
I am getting a Seg-fault end the end of the execution with the wiki example:

`$ kgs_explore --initial 2B6G.kgs.pdb`
> [...]
\> New structure: 2B6G.kgs_new_9.pdb .. Distance to initial: 0.822017 .. Distance to current target: 20 .. Null-space dimension: 94
\> New structure: 2B6G.kgs_new_10.pdb .. Distance to initial: 1.21946 .. Distance to current target: 17.8 .. Null-space dimension: 94
Took 24.3 seconds to generate 10 valid samples
Jacobian and null space computation took 1.82 seconds
Rigidity analysis took 5e-06 seconds
Node selection took 11 seconds
Segmentation fault (core dumped)

**Comment by vdbedem** [comment] 2017-01-27 05:02
Could you give a few details about hardware, OS, and compiler?

**Comment by RasmusFonseca** [comment] 2017-01-27 05:30
Just tried the same on Mac and it seemed to work. AFAIR @CoChrist is on Ubuntu, so I'll go and try that.

**Comment by CoChrists** [comment] 2017-01-27 17:46
The system is a x86_64 multicore with Ubuntu 14.04.5 LTS

>/data/KGS/debug# cmake -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_BUILD_TYPE=Debug ../src
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- /usr/bin/g++-5  -std=c++11
-- Found GSL: /usr
-- Found MKL: /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl/include
-- Configuring done
-- Generating done
-- Build files have been written to:  /data/KGS/debug

>/data/KGS/debug# make -j
[...]
/data/KGS/src/planners/BidirectionalMovingFront.cpp: In member function ‘virtual void BidirectionalMovingFront::generateSamples()’:
/data/KGS/src/planners/BidirectionalMovingFront.cpp:154:84: warning: casting ‘Direction*’ to ‘BlendedDirection&’ does not dereference pointer
       BlendedDirection &blendedDir = reinterpret_cast<BlendedDirection &>(direction);
                                                                                    ^
[...]
/data/KGS/debug# 

>/data/KGS/debug/test# gdb --args ../kgs_explore --initial 2B6G.kgs.pdb --samples 1
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ../kgs_explore...done.
(gdb) r
Starting program: /data/KGS/debug/kgs_explore --initial 2B6G.kgs.pdb --samples 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Sampling options:
        --initial 2B6G.kgs.pdb
        --annotation 
        --extraCovBonds 
        --workingDirectory /data/KGS/debug/test/
        --samples 1
        --radius 5
        --scaleToRadius 0
        --sampleRandom 1
        --gradient 0
        --collisionFactor 0.75
        --decreaseSteps 0
        --decreaseFactor 0.5
        --stepSize 1
        --maxRotation 0.174528
        --rejectsBeforeClose 10
        --metric rmsd
        --metricSelection heavy
        --planner binnedrrt
        --seed 418
        --saveData 1
        --alignAlways 0
        --alignIni 0
        --preventClashes 0
        --alignSelection heavy
        --gradientSelection heavy
        --root 1 
        --projectConstraints 1
        --collisionCheck all
        --svdCutoff 1e-12
        --collapseRigidEdges 0
Molecule has:
> 1969 atoms
> 8 initial collisions
> 68 constraints
> 578 DOFs of which 356 are cycle-DOFs
> 568 rigid bodies
Using nullspace move
Using random direction
Using binned RRT planner
[New Thread 0x7ffff7ff5700 (LWP 13634)]
[New Thread 0x7ffff0473700 (LWP 13635)]
[New Thread 0x7fffebfff700 (LWP 13636)]
[New Thread 0x7fffebbfe700 (LWP 13637)]
[New Thread 0x7fffeb7fd700 (LWP 13638)]
[New Thread 0x7fffeb3fc700 (LWP 13639)]
[New Thread 0x7fffeaffb700 (LWP 13640)]
[New Thread 0x7fffeabfa700 (LWP 13641)]
Total DOFs: 578, Cycle DOFs: 356, Max accessible DOFs: 316
Number of rigid clusters: 0, biggest cluster: index 0 with 0 atoms!
0 rigidified and 356 coordinated dihedrals
0 rigid out of 68 hydrogen bonds!
Sampling ...
\> New structure: 2B6G.kgs_new_1.pdb .. Distance to initial: 0.687887 .. Distance to current target: 20.9 .. Null-space dimension: 94
Took 16.1 seconds to generate 1 valid samples
Jacobian and null space computation took 0.428 seconds
Rigidity analysis took 2e-06 seconds
Node selection took 7.57 seconds
Program received signal SIGSEGV, Segmentation fault.
0x00000000004ebb01 in std::_List_iterator<Configuration*>::operator++ (this=0x7fffffffd520)
    at /usr/include/c++/5/bits/stl_list.h:159
159             _M_node = _M_node->_M_next;
(gdb) up
#1  0x00000000004eb648 in std::list<Configuration*, std::allocator<Configuration*> >::remove (this=0x847390, 
    __value=@0x7fffffffd568: 0xe3d610) at /usr/include/c++/5/bits/list.tcc:291
291               ++__next;
(gdb) up
#2  0x00000000004e9294 in Configuration::~Configuration (this=0xe3d610, __in_chrg=<optimized out>)
    at /data/KGS/src/core/Configuration.cpp:153
153         m_parent->m_children.remove(this);
(gdb) up
#3  0x0000000000529e90 in RRTPlanner::~RRTPlanner (this=0x849730, __in_chrg=<optimized out>)
    at /data/KGS/src/planners/RRTPlanner.cpp:107
107         delete pSmp;
(gdb) up
#4  0x0000000000529f46 in RRTPlanner::~RRTPlanner (this=0x849730, __in_chrg=<optimized out>)
    at /data/KGS/src/planners/RRTPlanner.cpp:110
110     }
(gdb) up
#5  0x00000000004dfaa3 in randomSampling (options=...) at /data/KGS/src/applications/MainExplore.cpp:204
204       delete planner;
(gdb) up
#6  0x00000000004e05b1 in main (argc=5, argv=0x7fffffffe298) at /data/KGS/src/applications/MainExplore.cpp:240
240       randomSampling(options);
(gdb) up
Initial frame selected; you cannot go up.
(gdb)

**Comment by RasmusFonseca** [comment] 2017-02-15 00:40
Hey @CoChrists I'm just catching up after arriving back in the states. I can't reproduce this on my mac or on red hat, but it looks like the error appears as the program is terminating, which should mean that all data has been written to the disk and aside from an error on termination, it should work. Is this so?

**Comment by RasmusFonseca** [comment] 2017-07-06 21:25
Closing as I can't reproduce. Will reopen if others see something similar.

**Closed by RasmusFonseca** 2017-07-06 21:25 UTC
